arch: ppc64le
  
dist: bionic
sudo: required
service: docker

script:
  - curl https://raw.githubusercontent.com/Siddhesh-Ghadi/travis-docker-mtu/master/.travis.yml
  - docker run -t centos:7 bash -c 'curl https://raw.githubusercontent.com/Siddhesh-Ghadi/travis-docker-mtu/master/.travis.yml'
