arch: ppc64le
  
dist: bionic
sudo: required
service: docker

script:
  - curl -sSL "http://storage.googleapis.com/kubernetes-release/release/v1.14.2/bin/linux/ppc64le/kubectl"
  - docker run -t centos:7 bash -c 'yum install curl -y && curl https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/linux-ppc64le/current_repodata.json'
